kind: Deployment
apiVersion: apps/v1
metadata:
  name: book-service
  namespace: default
spec:
  selector:
    matchLabels:
      name: book-service
  template:
    metadata:
      labels:
        name: book-service
    spec:
      containers:
        - name: book-service
          image: anthonyikeda/book-service:0.0.2-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://general-release-postgresql.default:5432/library_db
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: http://lgtm:4318/v1/logs
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://lgtm:4318/v1/traces
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: http://lgtm:4318/v1/metrics
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://lgtm:4318
            - name: OTEL_RESOURCE_ATTRIBUTES_DEPLOYMENT_ENVIRONMENT
              value: docker
            - name: OTEL_RESOURCE_ATTRIBUTES_SERVICE_NAME
              value: book-service
            - name: OTEL_RESOURCE_ATTRIBUTES_SERVICE_NAMESPACE
              value: library
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"

