{
 "title": "PoC Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId" }
  ]
 },
 "panels": [
  {
   "title": "Book Server Http Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{job=\"library/book-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Book Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"book-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "9628b1eb", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "${traceId}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Book Service Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "filters": [
      { "id": "edb70ead", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "book-service" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}